---
title: "Spatial Data Analysis"
author: "Robby Butarbutar"
date: "12/4/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This folder contains analysis for spatial data attributed to conservation surveys in PT Austindo Nusantara Jaya. For confidentiality, the shapefiles containing sensitive information such as concession boundaries and so on will be kept hidden. 

One R script in master folder of *spatial_data_analysis* is [`read_landsat.R`](https://github.com/robbybinsar/Konservasi_ANJ/blob/master/spatial_data_analysis/read_landsat.R), This script contains number of ways to read landsat data into R

Currently there are 2 folders named based on the subsidiaries of PT ANJ that have GIS - Conservation related projects/ activities.

* folder **KAL** : Contains R codes for manipulating spatial data and visualizing survey of Orang utan in PT KAL conservation area
* folder **SMM** : Contains R codes for manipulating spatial data and visualizing survey of Tarsius Belitung in PT SMM Conservation area





    