---
title: "Above Ground Biomass and Carbon Sequestration PT SMM"
subtitle: "Hutan Sekunder Bentang Alam Makam Balok"
author: "Robby B"
date: "11/17/2020"
output:
  word_document:
    toc: yes
  pdf_document:
    toc: yes
    latex_engine: lualatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Load packages

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(BIOMASS)
library(knitr)
```

### 2. Reading and preparing data

```{r}
primer <- read.csv("./primer_tree_measurement.csv")
sekunder <- read.csv("./secunder_tree_measurement.csv")
```

### 3. Retrieve wood density

```{r}
##Check and retrieve taxonomy First, check for any typo in the taxonomy
  Taxo <- correctTaxo(genus = primer$genus, species = primer$species, useCache = T, verbose = F)
  primer$genusCorr <- Taxo$genusCorrected
  primer$speciesCorr <- Taxo$speciesCorrected
  #If needed, retrieve APG III families and orders from genus names
  APG <- getTaxonomy(primer$genusCorr, findOrder = T)
  primer$familyAPG <- APG$family
  primer$orderAPG <- APG$order
  #Retrieve wood density using the plot level average if no genus level information is available
  dataWD <- getWoodDensity(
    genus = primer$genusCorr,
    species = primer$speciesCorr,
    stand = primer$plotId
  )
```


### 4. Build Height-Diameter Models

```{r}
##compare different models at once
  result <- modelHD(
    D = sekunder$D,
    H = sekunder$H,
    useWeight = TRUE
  )
  kable(result)
  ##Compute the local H-D model with the lowest RSE
  HDmodel <- modelHD(
    D = sekunder$D,
    H = sekunder$H,
    method = "log2",
    useWeight = TRUE
  )
```

### 5. Retrieve Height Data

```{r}
##Retrieve height data from a local Height-diameter model
  dataHlocal <- retrieveH(
    D = primer$D,
    model = HDmodel)
  ##Retrieve height data from a Feldpaush et al. (2012) averaged model
  dataHfeld <- retrieveH(
    D = primer$D,
    region = "SEAsia")
  ##Retrieve height data from Chave et al. (2012) equation 6
  dataHchave <- retrieveH(
    D = primer$D,
    coord = primer[, c("long", "lat")])
```

### 6. Estimate AGB (Above Ground Biomass)

```{r}
##organize data
  primer$WD <- dataWD$meanWD
  primer$H <- dataHlocal$H
  primer$Hfeld <- dataHfeld$H
  ##Compute AGB(Mg) per tree
  AGBtree <- computeAGB(
    D = primer$D,
    WD = primer$WD,
    H = primer$H)
  ##Compute AGB(Mg) per plot (need to be divided by plot area to get Mg/ha)
  AGBplot <- summaryByPlot(AGBtree, primer$plotId)
  AGBplot$TonHa <- AGBplot$AGB*100
  kable(AGBplot)
  ##Compute AGB(Mg) per tree without height information (Eq. 7 from Chave et al. (2014))
  AGBplotChave <- summaryByPlot(
    computeAGB(
      D = primer$D, WD = primer$WD,
      coord = primer[, c("long", "lat")]),
    primer$plotId)
  ##Compute AGB(Mg) per tree with Feldpausch et al. (2012) regional H-D model
  AGBplotFeld <- summaryByPlot(
    computeAGB(
      D = primer$D, WD = primer$WD,
      H = primer$Hfeld
    ),
    plot = primer$plotId)
  ##Mean AGB
  mean(AGBplot$TonHa)
  ##Carbon sequesttration
  mean(AGBplot$TonHa)/2
```

### 7. Propagate AGB Errors

```{r}
##Organize data
  primer$sdWD <- dataWD$sdWD
  primer$HfeldRSE <- dataHfeld$RSE
  ##Propagate error for all tree at once using the local HD model constructed above (modelHD), 
  ##i.e. non-independent allometric errors will be assigned to all trees at each iteration, independently of plots.
  resultMC <- AGBmonteCarlo(D = primer$D, WD = primer$WD, errWD = primer$sdWD, HDmodel = HDmodel, Dpropag = "chave2004")
  Res <- summaryByPlot(resultMC$AGB_simu, primer$plotId)
  Res <- Res[order(Res$AGB), ]
  plot(Res$AGB, pch = 20, xlab = "Plots", ylab = "AGB", ylim = c(0, max(Res$Cred_97.5)), las = 1, cex.lab = 1.3)
  segments(seq(nrow(Res)), Res$Cred_2.5, seq(nrow(Res)), Res$Cred_97.5, col = "red")
  ##Using the Feldpaush regional HD averaged model (code only given)
  resultMC <- AGBmonteCarlo(
    D = primer$D,
    WD = primer$WD,
    errWD = primer$sdWD,
    H = primer$Hfeld,
    errH = primer$HfeldRSE,
    Dpropag = "chave2004"
  )
  
  Res <- summaryByPlot(resultMC$AGB_simu, primer$plotId)
  Res <- Res[order(Res$AGB), ]
  plot(Res$AGB, pch = 20, xlab = "Plots", ylab = "AGB", ylim = c(0, max(Res$Cred_97.5)), las = 1, cex.lab = 1.3)
  segments(seq(nrow(Res)), Res$Cred_2.5, seq(nrow(Res)), Res$Cred_97.5, col = "red")
  ##Per plot using the Chave et al. (2014) Equation 7 (code only given)
  resultMC <- AGBmonteCarlo(
    D = primer$D,
    WD = primer$WD,
    errWD = primer$sdWD,
    coord = primer[, c("long", "lat")],
    Dpropag = "chave2004"
  )
  Res <- summaryByPlot(resultMC$AGB_simu, primer$plotId)
  Res <- Res[order(Res$AGB), ]
  plot(Res$AGB, pch = 20, xlab = "Plots", ylab = "AGB", ylim = c(0, max(Res$Cred_97.5)), las = 1, cex.lab = 1.3)
  segments(seq(nrow(Res)), Res$Cred_2.5, seq(nrow(Res)), Res$Cred_97.5, col = "red")
```


