---
title: "| Indeks Keanekaragaman Region 1 dan 2 \n| Apr - Jun 2021\n"
author: |
  | Robby B
  | Conservation Data Assistant
date: "07/20/2021"
output:
  pdf_document:
    toc: yes
    latex_engine: lualatex
  word_document:
    toc: yes
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/My R/Konservasi_ANJ')
```

**Load packages**

```{r a, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(plotly)
library(hrbrthemes)
library(openxlsx)
library(knitr)
library(png)
library(grid)
library(cowplot)
library(magick)
```

```{r b}
subjek <- "Region 1 & 2"
range_x <- "April - Juni 2021"
filedata <- "C:/Users/robby/Documents/My R/Konservasi_ANJ/Diversity_measures/indeks_kehati/data_jml_spesies_ANJ.xlsx"
```

\blandscape
## A. Diversity Index

```{r c, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
data <- read.xlsx(filedata, sheet = "grafik_keanekaragaman",
    detectDates = TRUE)
data <- 
    #data[!(data$sites!="PMP"),]
    data[!(data$sites == "ANJAP"| data$sites=="PMP"|data$sites=="PPM"),]
    #data[!(data$sites != "ANJAP"& data$sites!= "PMP"& data$sites!= "PPM"),]
kable(data, format = "pipe", caption = "Diversity index Apr - Jun 2021")
attach(data)
```


```{r d, fig.width=9, fig.height=6,echo=FALSE, fig.align='center', warning=FALSE}
div <- ggplot(data, aes(x=date, y=diversity_index, group = sites, color = sites )) +
    #geom_line(stat = "smooth", size =1) + #change stat to "identity" for straight line
    #polynomial regression, adjust the poly degree to get a desired line of best fit.
    stat_smooth(method = "lm", formula = y~poly(x, 2), size = 1.2, se = F)+ 
    geom_point()+
    geom_hline(yintercept=1, color="red", size=.5) +
    geom_hline(yintercept =3.322, color = "orange", size = .5)+
    geom_text(aes(label = round(diversity_index,2)), size = 3, 
              position = position_dodge(width = 0), vjust = -0.5, hjust = 0) +
    scale_y_continuous(breaks = seq(0,5,0.5))+
    scale_x_date(date_labels = "%b", breaks = "1 month")+
    scale_color_manual("Sites", values = c("dark blue","purple","dark green", "brown"))+
    theme_bw() + 
    labs(title = paste("Grafik Indeks Keanekaragaman", subjek, range_x), 
         subtitle = "Method: Shannon-Wiener \nPolynomial degree: 2",
         x = "Month", y = "Diversity Index")+
    annotate(geom="text", x= as.Date("2021-02-15", "%Y-%m-%d"), y= 0.95 , 
             label="1 = Batas indeks keanekaragaman kategori rendah",size = 3)+
    annotate(geom="text", x = as.Date("2021-02-15", "%Y-%m-%d"), y=3.5, 
             label="3.322 = Batas indeks keanekaragaman kategori tinggi", size = 3) +
    theme(
        axis.text = element_text(face = "bold", size = 11),
        axis.title = element_text(size = 12, face = "bold"),
        plot.margin = margin(1,1,1,1,"cm"),
        plot.background = element_rect(colour = "black"))

ggdraw() + draw_plot(div) +
  draw_image("anj.png", scale = .15, x = 0.4, y=0.45)
```


## B. Species Number

```{r e, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
data <- read.xlsx(filedata, sheet = "species_number",
    detectDates = TRUE)
data <- 
    #data[!(data$sites!="PMP"),]
    data[!(data$sites == "ANJAP"| data$sites=="PMP"|data$sites=="PPM"),]
    #data[!(data$sites != "ANJAP"& data$sites!= "PMP"& data$sites!= "PPM"),]
kable(data, format = "pipe", caption = paste("Jumlah Spesies", range_x))
attach(data)
```

```{r f, fig.width=9, fig.height= 6.5,echo=FALSE, fig.align='center', warning=FALSE}
anj <- readPNG("anj.png")
grafik <- ggplot(data, aes(x = date, y = species.number, fill = sites)) + 
    geom_bar(stat = 'identity', position = position_dodge(), width = 12) +
    scale_fill_manual("Sites", values = c("dark blue","purple","dark green", "brown"))+
    scale_x_date(date_labels = "%b", breaks = "1 month")+
    scale_y_continuous(breaks = seq(0,200,10))+
    geom_text(aes(label= species.number),hjust=0.5, vjust=-1,size=3, 
              position = position_dodge(width = 12), color = "red")+
    labs(x = "Month", y = "Jumlah Spesies", title = paste("Jumlah Spesies", subjek),
         subtitle = range_x)+
    theme_bw() +
    theme(panel.background = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title = element_text(size = rel(1.5),face = "bold",hjust=0),
          axis.title = element_text(face="bold"),
          axis.title.y = element_text(vjust = 3,size = 11),
          axis.title.x = element_text(vjust=-1, size=11),
          axis.line = element_line(colour="black"),
          axis.text = element_text(size = 10,color = "black", face = "bold"),
          legend.text = element_text(size=10, face = "bold"),
          legend.title = element_text(size = 10, face = "bold"),
          plot.subtitle = element_text(size = 13),
          plot.margin = margin(1,1,1,1,"cm"),
          plot.background = element_rect(colour = "black"))

ggdraw() + draw_plot(grafik) +
  draw_image("anj.png", scale = .15, x = 0.4, y=0.45)
```


## C. Population Size

```{r g, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
data <- read.xlsx(filedata, sheet = "size",
    detectDates = TRUE)
data <- 
    #data[!(data$sites!="PMP"),]
    data[!(data$sites == "ANJAP"| data$sites=="PMP"|data$sites=="PPM"),]
    #data[!(data$sites != "ANJAP"& data$sites!= "PMP"& data$sites!= "PPM"),]
kable(data, format = "pipe", caption = paste("Total individu", range_x))
attach(data)
```

```{r h, fig.width=9, fig.height=6,echo=FALSE, fig.align='center', warning=FALSE}
anj <- readPNG("anj.png")
grafik <- ggplot(data, aes(x = date, y = size, fill = sites)) + 
    geom_bar(stat = 'identity', position = position_dodge(), width = 12) +
    scale_fill_manual("Sites", values = c("dark blue","purple","dark green", "brown"))+
    scale_x_date(date_labels = "%b", breaks = "1 month")+
    scale_y_continuous(breaks = seq(0,5000,100))+
    geom_text(aes(label= size),hjust=0.5, vjust=-1,size=3, 
              position = position_dodge(width = 12), color = "red")+
    labs(x = "Month", y = "Total individu", title = paste("Population Size", subjek),
         subtitle = range_x)+
    theme_bw() +
    theme(panel.background = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title = element_text(size = rel(1.5),face = "bold",hjust=0),
          axis.title = element_text(face="bold"),
          axis.title.y = element_text(vjust = 3,size = 11),
          axis.title.x = element_text(vjust=-1, size=11),
          axis.line = element_line(colour="black"),
          axis.text = element_text(size = 10,color = "black", face = "bold"),
          legend.text = element_text(size=10, face = "bold"),
          legend.title = element_text(size = 10, face = "bold"),
          plot.subtitle = element_text(size = 13),
          plot.margin = margin(1,1,1,1,"cm"),
          plot.background = element_rect(colour = "black"))

ggdraw() + draw_plot(grafik) +
  draw_image("anj.png", scale = .15, x = 0.4, y=0.45)
```
\elandscape


  