---
title: "| Diversity Measures Region 3 \n| January - September 2020\n"
author: |
  | Robby B
  | Conservation Data Assistant
date: "10/30/2020"
output:
  pdf_document:
    toc: yes
    latex_engine: lualatex
  word_document:
    toc: yes
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Load packages**

```{r a, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(plotly)
library(hrbrthemes)
library(openxlsx)
library(knitr)
library(png)
library(grid)
library(cowplot)
library(magick)
```

```{r b}
subjek <- "Region 3"
range_x <- "Jan - Sep 2020"
filedata <- "C:/Users/robby/Documents/My R/Konservasi_ANJ/Diversity_measures/indeks_kehati/data_jml_spesies_ANJ.xlsx"
```

\newpage
## A. Species Richness Index 

```{r c, message=FALSE, warning=FALSE, echo=FALSE}
data <- read.xlsx(filedata, sheet = "grafik_kekayaan",
    detectDates = TRUE)
data <- 
    #data[!(data$sites!= "PMP"),]
    #data[!(data$sites == "ANJAP"| data$sites=="PMP"|data$sites=="PPM"),]
    data[!(data$sites != "ANJAP"& data$sites!= "PMP"& data$sites!= "PPM"),]
kable(data, format = "pipe", caption = "Species Richness index Jan-Sep 2020")
attach(data)
```

\newpage
\blandscape

```{r d, fig.width=9, echo= FALSE, fig.align='center'}
anj <- readPNG("anj.png")
rch <- ggplot(data, aes(x=date, y=richness_index, group = sites, color = sites )) +
    #geom_line(stat = "smooth", size =1) + #change stat to "identity" for straight line
    #polynomial regression, adjust the poly degree to get a desired line of best fit.
    stat_smooth(method = "lm", formula = y~poly(x, 2), size = 1.2, se = F)+ 
    geom_point()+
    geom_hline(yintercept=3.5, color="red", size=.5) +
    geom_hline(yintercept = 5, color = "orange", size = .5)+
    geom_text(aes(label = round(richness_index,2)), size = 3, 
              position = position_dodge(width = 0), vjust = -0.5, hjust = 0) +
    scale_y_continuous(breaks = seq(0,20,1))+
    scale_x_date(date_labels = "%b", breaks = "1 month") +
    theme_bw() + 
    labs(title = paste("Grafik Indeks Kekayaan Spesies", subjek, range_x), 
         subtitle = "Method: Margalef \nPolynomial degree: 2")+
    annotate(geom="text", x= as.Date("2020-02-20", "%Y-%m-%d"), y=3.4, 
             label="3.5 = Batas indeks kekayaan kategori rendah",size = 3)+
    annotate(geom="text", x = as.Date("2020-02-20", "%Y-%m-%d"), y=5.2, 
             label="5 = Batas indeks kekayaan kategori tinggi", size = 3) +
    theme(
        axis.text = element_text(face = "bold"))+
    xlab("Bulan") + ylab("Indeks Kekayaan")
    
ggdraw() + draw_plot(rch)+
  draw_image("anj.png", scale = .15, x = 0.4, y=0.44)
    
```

\elandscape

\newpage
## B. Diversity Index

```{r e, message=FALSE, warning=FALSE, echo=FALSE}
data <- read.xlsx(filedata, sheet = "grafik_keanekaragaman",
    detectDates = TRUE)
data <- 
    #data[!(data$sites!="PMP"),]
    #data[!(data$sites == "ANJAP"| data$sites=="PMP"|data$sites=="PPM"),]
    data[!(data$sites != "ANJAP"& data$sites!= "PMP"& data$sites!= "PPM"),]
kable(data, format = "pipe", caption = "Diversity index Jan- Sep 2020")
attach(data)
```
\newpage
\blandscape

```{r f, fig.width=9, echo=FALSE, fig.align='center'}
div <- ggplot(data, aes(x=date, y=diversity_index, group = sites, color = sites )) +
    #geom_line(stat = "smooth", size =1) + #change stat to "identity" for straight line
    #polynomial regression, adjust the poly degree to get a desired line of best fit.
    stat_smooth(method = "lm", formula = y~poly(x, 2), size = 1.2, se = F)+ 
    geom_point()+
    geom_hline(yintercept=1, color="red", size=.5) +
    geom_hline(yintercept =3.322, color = "orange", size = .5)+
    geom_text(aes(label = round(diversity_index,2)), size = 3, 
              position = position_dodge(width = 0), vjust = -0.5, hjust = 0) +
    scale_y_continuous(breaks = seq(0,5,0.5))+
    scale_x_date(date_labels = "%b", breaks = "1 month")+
    theme_bw() + 
    labs(title = paste("Grafik Indeks Keanekaragaman", subjek, range_x), 
         subtitle = "Method: Shannon-Wiener \nPolynomial degree: 2")+
    annotate(geom="text", x= as.Date("2020-05-05", "%Y-%m-%d"), y= 0.95 , 
             label="1 = Batas indeks keanekaragaman kategori rendah",size = 3)+
    annotate(geom="text", x = as.Date("2020-05-08", "%Y-%m-%d"), y=3.4, 
             label="3.322 = Batas indeks keanekaragaman kategori tinggi", size = 3) +
    theme(
        axis.text = element_text(face = "bold"))

ggdraw() + draw_plot(div) +
  draw_image("anj.png", scale = .15, x = 0.4, y=0.44)
```

\elandscape

\newpage
## C. Evenness Index

```{r g, message=FALSE, warning=FALSE, echo=FALSE}
data <- read.xlsx(filedata, sheet = "grafik_kemerataan",
    detectDates = TRUE)
data <- 
    #data[!(data$sites!= "PMP"),]
    #data[!(data$sites == "ANJAP"| data$sites=="PMP"|data$sites=="PPM"),]
    data[!(data$sites != "ANJAP"& data$sites!= "PMP"& data$sites!= "PPM"),]
kable(data, format = "pipe", caption = "Evenness index Jan-Sep 2020")
attach(data)
```
\newpage
\blandscape

```{r h, fig.width=9, echo=FALSE, fig.align='center'}
evenn <- ggplot(data, aes(x=date, y=evenness_index, group = sites, color = sites )) +
    #geom_line(stat = "smooth", size =1) + #change stat to "identity" for straight line
    #polynomial regression, adjust the poly degree to get a desired line of best fit.
    stat_smooth(method = "lm", formula = y~poly(x, 2), size = 1.2, se = F)+ 
    geom_point()+
    geom_hline(yintercept=0.5, color="red", size=.5) +
    geom_hline(yintercept =0.75, color = "orange", size = .5)+
    geom_text(aes(label = round(evenness_index,2)), size = 3, 
              position = position_dodge(width = 0), vjust = -0.5, hjust = 0) +
    scale_y_continuous(breaks = seq(0,1,0.1))+
    scale_x_date(date_labels = "%b", breaks = "1 month") +
    theme_bw() + 
    labs(title = paste("Grafik Indeks Kemerataan", subjek, range_x), 
         subtitle = "Method: Shannon-Wiener \nPolynomial degree: 2")+
    annotate(geom="text", x= as.Date("2020-02-29", "%Y-%m-%d"), y= 0.49 , 
             label="0.5 = Batas indeks kemerataan kategori rendah",size = 3)+
    annotate(geom="text", x = as.Date("2020-02-29", "%Y-%m-%d"), y=0.77, 
             label="0.75 = Batas indeks kemerataan kategori tinggi", size = 3) +
    theme(
        axis.text = element_text(face = "bold"))

ggdraw() + draw_plot(evenn) +
  draw_image("anj.png", scale = .15, x = 0.4, y=0.44)
```

\elandscape